# Demos for talk 'Unexpected Monad. Is Safe Error Handling Possible in JavaScript/TypeScript?'

> Please go to the last commit to view the full content.

Stage: `try/catch` with `async/await.
